name: Build and test

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/ 
        key: ${{ runner.os }}-cargo
        restore-keys: ${{ runner.os }}-cargo
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Install scripts runtime
      run: pnpm install
    - name: Run tests
      run: pnpm run test
    - name: Run build
      run: pnpm run build